### ISSUE TITLE
Feature request: respect possibleAnchors order

### ISSUE THREAD

**Issue by rijk** [everweij/react-laag#11]
Given the following config:

```
possibleAnchors: [
  anchor.RIGHT_CENTER,
  anchor.BOTTOM_CENTER,
  anchor.LEFT_CENTER,
  anchor.BOTTOM_LEFT,
  anchor.BOTTOM_RIGHT,
  anchor.TOP_CENTER,
]
```

I would expect this menu to be placed BOTTOM_CENTER:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/159500/68071719-5a588200-fd7d-11e9-94dd-cec012f6b328.png">

And this one to be LEFT_CENTER:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/159500/68071730-70fed900-fd7d-11e9-8e29-07664f25924e.png">

Right now, it seems to pick somewhat randomly from the available options. Could this behaviour be changed so it picks the first available option?

**Comment by everweij** [comment]
Hi Rijk,
Again, good question!
It's true that defining `possibleAnchors` has no effect on the anchor priority.
There is, however, some logic / rationale to which determines the anchor priority dynamically. This function looks at `anchor` (the 'preferred' anchor), `preferX`, `preferY` and `possibleAnchors`, and outputs a list of anchors sorted by priority. It than tries to find the first one that 'fits'.

This prioritising is currently **implicit**, which I think will work for many use-cases (together with `preferX/Y`). However, there may be use-cases where you want to prioritise the anchors *explicitly*. 

How would you define such behavior? Right now, `possibleAnchors` just sets the available anchors. I don't think that this prop should do 2 things. Maybe an extra prop: `anchorPriority`? Or maybe a flag `respectAnchorPriority` that 'respects' / overrides the priority based on `possibleAnchors`? 😅

What do you think?

**Comment by Rijk** [comment]
If you ask me, this is not important enough to add another property for. I thought it could 'just work'  like this, and that would be pretty nice. In this case I wanted `BOTTOM_LEFT`/`BOTTOM_RIGHT` to be used only as a last resort. It seems `preferX`/`preferY` cannot really help here.

But yeah, it is not super important, and if there's other considerations here I understand.

**Comment by everweij** [comment]
I do think your wish is legitimate, but as a consequence it add more complexity. Will keep this open for now and see if others are running into the same issue as well...

**Comment by rijk** [comment]
I'll close this as it's not that important.
