### ISSUE TITLE
Accessibility Features?

### ISSUE THREAD

**Issue by pebcakerror** [everweij/react-laag#17]
Does this library have accessibility features similar to downshift and react-beautiful-dnd that were mentioned in the introductory block post?

**Comment by everweij** [comment]
Hi Jonathan,
I'm afraid react-laag currently has no real accessibility features such as aria-labels and keyboard navigation. I plan to add this in a future release. For the time being you could use downshift's `useSelect` for menu's, or add some aria-* stuff manually (sorry, not ideal I know).

I will leave this issue open for now. If you have any other questions, please let me know.
