### ISSUE TITLE
Ability to pass custom window/document instances

### ISSUE THREAD

**Issue by anilanar** [everweij/react-laag#19]
When rendering into iframes/shadow-dom, global `window` and `document` refer to different instances than those that are rendered in. A similar capability to `downshift`'s `environment` prop is needed.

**Comment by everweij** [comment]
Hi Anil, thanks for reporting this issue!
Interesting point, I haven't encountered a scenario where I needed the feature you propose, but I'm cool with implementing it. Will make a draft as soon as I have time!

**Comment by anilanar** [comment]
Cool thanks. Our scenario is rendering “widgets” into iframes (`<Frame>Hello world</Frame>`) to avoid CSS side effects from parent websites. That’s a very niche requirement; but lucky for us, emotion/styled-components also supports it.

**Comment by everweij** [comment]
Hi, I created a draft for the `environment` prop in v1.6.0. See https://react-laag.com/docs/togglelayer/#environment .
Can you check if this works for you?

**Comment by chrissysemens** [comment]
Hi all,

I'm sturggling to get the environment property to work. I've got a window instance and passing the window to the environment prop. But the layers div still is always rendered within the base page that opens the new window.

Am I missing something? Any help appreciated.
