### ISSUE TITLE
The arrow position is not aligned to the tooltip if the toggle element is too large

### ISSUE THREAD

**Issue by yuri-kulikov** [everweij/react-laag#21]
The arrow position is not aligned to the tooltip if the toggle element is too large and we use a corner anchor:
![Kapture 2019-12-10 at 14 01 26](https://user-images.githubusercontent.com/42337914/70524221-c20ca480-1b55-11ea-9472-00697968158a.gif)

**Comment by everweij** [comment]
Hi Yuri, thanks for reporting this issue!
Also thanks for the GIF, very helpful 👍🏼

Although I only came across scenario's where the toggle element is always smaller then the layer, I definitely think we should support cases where the trigger element is _bigger_ than the layer.
What is the behaviour you're expecting?
Personally, I think the example below looks the nicest:

<img width="311" alt="Screen Shot 2019-12-10 at 17 19 55" src="https://user-images.githubusercontent.com/25911714/70547816-d6f73100-1b71-11ea-876f-03aafd061df4.png">

**Comment by yuri-kulikov** [comment]
@everweij, thanks for the quick response!

> Personally, I think the example below looks the nicest: \<img>

Yeah, that's what I think I'd expect to see 👍 

One more thought (probably obvious 🙂 ): I feel that this solution can be a bit tricky, because if the trigger is small again and we use the “diagonal” anchor and align the arrow to the center of the tooltip, there may be the opposite problem.

**Comment by everweij** [comment]
I've just pushed v1.6.0, which should fix this issue.
Can you check / confirm whether this works for you?
![bigger-smaller-trigger](https://user-images.githubusercontent.com/25911714/70569155-ad520000-1b99-11ea-81bc-e524273f59d3.gif)

**Comment by yuri-kulikov** [comment]
🚀 Yeap, it works for me!

But I've found an issue:
![Kapture 2019-12-11 at 11 28 25](https://user-images.githubusercontent.com/42337914/70604769-3ef95600-1c0a-11ea-9eb4-345784c5f9cc.gif)
![Kapture 2019-12-11 at 11 30 40](https://user-images.githubusercontent.com/42337914/70604777-43257380-1c0a-11ea-99a7-4fcbfcd11f60.gif)

**Comment by everweij** [comment]
Ah snap, good catch! 😅
Jup, need to fix that!

**Comment by everweij** [comment]
I think I've fixed it :)

**Comment by yuri-kulikov** [comment]
Thank you, works great! 👍
