### ISSUE TITLE
Docs: autoAdjust logic description

### ISSUE THREAD

**Issue by mtmacdonald** [everweij/react-laag#28]
Is it possible to have some more documentation on the logic behind autoAdjust?

For example, how does it respond regarding container margins, padding, and different container overflow properties?

**Comment by everweij** [comment]
Good question!
I'm planning to add a section to the documentation explaining the strategy behind the positional logic. Hopefully, this will clarify some things for people who want to use react-laag, and for people who are interested in contributing.

**Comment by everweij** [comment]
Hi @mtmacdonald ,
This issue has been open for almost a year now 😅.
I've added a section to the readme yesterday covering this topic: https://github.com/everweij/react-laag#placement-priority
If you have time, can you take a look it this, and tell me if it's clear enough?
Thanks!

**Comment by everweij** [comment]
I'm closing this issue for now. If you want, you can re-open this issue any time or open a new one.

**Comment by mtmacdonald** [comment]
Sorry for the slow reply. I appreciate the v2 docs structure and this update - it's also much clearer now we don't have `ToggleLayer` and `useToggleLayer`. Thanks!
