### ISSUE TITLE
Problem with default isOpen=true

### ISSUE THREAD

**Issue by gizmooo** [everweij/react-laag#30]
Laag does not wait for a delay in rendering React at the default value "isOpen = true" and throws an error:
> Could not find a valid reference of the trigger element. See https://www.react-laag.com/docs/togglelayer/#children for more info.
 
 
```
default value
isOpen=true
```

**case**
When the page is displayed, the tooltip should be visible

sandbox with error
```
const [show, toggle] = useState(true);
```
https://codesandbox.io/s/busy-night-3pjt5?fontsize=14&hidenavigation=1&theme=dark

**Comment by everweij** [comment]
Hi @gizmooo,
Thanks for reporting this issue, and sorry for my late response!

I've just published v0.7.1, and hopefully this bug should be fixed now.
Let me know if this works for you.

Erik
