### ISSUE TITLE
Autofocus causing scroll

### ISSUE THREAD

**Issue by zeitvertrieb** [everweij/react-laag#31]
Hello, great component. one question: I tested a menu accessible (as described here: https://dev.to/everweij/accessible-and-adaptive-select-menu-s-using-react-laag-and-downshift-abn)
But since the Menu is rendered in DOM not in root and right before body end the autofocus causes a automatic scroll to the end of my view (although the menu is in the header).
I hope I did describe this clearly. any ideas. thanks. 
(-- I believe it actually is a downshift topic. so probably the wrong spot here.)

**Comment by everweij** [comment]
Thanks @zeitvertrieb for reporting this issue! I will need to do some investigation first. Do you have something like a codesandbox you can share, so I can reproduce the issue?

**Comment by zeitvertrieb** [comment]
Hi @everweij, I use the experimental feature: container on the ToggleLayer. seems to work fine – if the parent container is not set to relative or absolute position.
