### ISSUE TITLE
useTooltip documentation missing

### ISSUE THREAD

**Issue by TheTedAdams** [everweij/react-laag#33]
The `useTooltip` documentation linked in the sidebar of the docs page is not there. Clicking the link does not navigate, and putting the URL in manually gets a 404.

The sidebar links to https://www.react-laag.com/docs/usetooltip/

**Comment by everweij** [comment]
Thanks for reporting this @TheTedAdams, I will into it asap!

**Comment by everweij** [comment]
Fixed it!
