### ISSUE TITLE
Mechanism for handling open/close behavior of related toggle-layers

### ISSUE THREAD

**Issue by everweij** [everweij/react-laag#34]
Right now, it's tricky to get things like nested menu's working...

**Comment by ratacat** [comment]
@everweij I'm trying to build a non-nested menu with react-laag, I'm still learning React.  Would you be able to point me to any documentation on how to keep the ToggleLayer open while the mouse is over the trigger as WELL as the ToggleLayer?  Im just trying to build a norm hover menu item...

**Comment by everweij** [comment]
This is been taken care of in v2.0.0.
See https://storybook.react-laag.com/?path=/docs/nested-menu-s--page for an example and https://github.com/everweij/react-laag#nesting for docs.
