### ISSUE TITLE
Tooltip example shows error in Safari

### ISSUE THREAD

**Issue by Rijk** [everweij/react-laag#4]
https://www.react-laag.com/docs#tooltip

Both on Mac and iPhone:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/159500/66702168-f8b87100-ed04-11e9-8c1a-e707839d66d2.png">

The docs include a reference to this:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/159500/66702310-85176380-ed06-11e9-8171-c0cd9b5e0b2f.png">

So I think it would be best to include this fix in the examples, no?

**Comment by everweij** [comment]
Thanks Rijk for taking the time to notify me about this. You're absolutely right, I hadn't thought about including a polyfill in the examples. Right now, I'm on a little trip this weekend, but I will update the examples as soon as I'm home again. I will get back at you!

**Comment by Rijk** [comment]
Thanks. Great package by the way, checked it out in detail today! Beautiful docs + API.

**Comment by everweij** [comment]
Thanks Rijk! I've updated the CodeBox samples with a polyfill. I'm gonna close this issue for now. Please let me know if you're experiencing futher browser compatibility issues.
