### ISSUE TITLE
It doesn't react to resize or scroll when using hooks

### ISSUE THREAD

**Issue by eden-lane** [everweij/react-laag#40]
Example:
https://codesandbox.io/s/icy-bush-kj4qv

**Comment by maxime4000** [comment]
I think I have the same problems than you, but I can't validate because the codesandbox link is dead. When I use useToggleLayer and openWithRef, the toggle layers isn't following the ref when I scroll down. but if I use openFromMouseEvent it follow the element. Is that the same case than you ?

**Comment by everweij** [comment]
This issue should be fixed in V2.

I will close this issue for now. If you run into the same problem again after upgrading, please don't hesitate to re-open this issue (or open a new one).

Thanks,
Erik
