### ISSUE TITLE
Input validation example doesn't position dropdown correctly

### ISSUE THREAD

**Issue by hinok** [everweij/react-laag#45]
Hey,
I think that [input validation example](https://www.react-laag.com/examples/inputvalidation/) has a small issue with positioning dropdown in one case.

**Demo below**

<img width="958" alt="Zrzut ekranu 2020-05-22 o 20 49 24" src="https://user-images.githubusercontent.com/1313605/82699966-d361ed00-9c6d-11ea-8ce9-21e08dbfe95f.png">

**Gif**

![demo](https://user-images.githubusercontent.com/1313605/82699817-a3b2e500-9c6d-11ea-9406-ce000c5b4eb0.gif)

**Comment by everweij** [comment]
Hi @hinok ,
Sorry for my late response, and thanks for noticing this!
I've updated most of the examples and this bug should be gone by now.
You can check out the new version here: https://storybook.react-laag.com/?path=/docs/password-validation--page

**Comment by everweij** [comment]
I will close this issue for now. Feel free to open a new issue if you spot something odd, or want to report something else!

**Comment by hinok** [comment]
Hey @everweij 
I think that the issue still exists here https://storybook.react-laag.com/?path=/docs/password-validation--page

Look at the video

![Kapture 2020-12-18 at 11 02 02](https://user-images.githubusercontent.com/1313605/102601693-d13b1080-4120-11eb-9b2c-7017a83764b9.gif)

On the other hand I cannot replicate that buggy behaviour here: https://storybook.react-laag.com/?path=/docs/popover-menu--page, so maybe it's just a matter of proper configuration?

**Comment by everweij** [comment]
@hinok thanks,
Apparently, I forgot to add the "left-center" placement as possible-placement in the options.
I've pushed a small fix, so the layer should be visible on the left side as well :)
