### ISSUE TITLE
Hover (scale transform) of trigger element messes up the layer's position when using the fixed prop

### ISSUE THREAD

**Issue by everweij** [everweij/react-laag#6]

**Comment by everweij** [comment]
@Rijk, since I've been working on #5 I'm not able to reproduce this bug anymore. Or maybe I've interpreted it wrong. Do you think it is still a bug? In that case, could you tell me a bit more about it?

**Comment by Rijk** [comment]
Yep, seems to be fixed! The repositioning is also really snappy btw, no lag at all. 👌
