### ISSUE TITLE
Allow no parameters in useHover()

### ISSUE THREAD

**Issue by Rijk** [everweij/react-laag#7]
Small one: it would be nice if `useHover()` wouldn’t trigger an error.

* `const [ show, hoverProps ] = useHover({})` -> works (defaults are used)
* `const [ show, hoverProps ] = useHover()` -> error ("cannot destructure null or undefined")

**Comment by everweij** [comment]
I agree! That's an easy one ;) I will add this in the next release.

**Comment by everweij** [comment]
This should be fixed in v1.4.0 :)
