### ISSUE TITLE
[FEATURE] add possibility to interact with elements in tooltip when using "UseHover" hook

### ISSUE THREAD

**Issue by Gussarah** [everweij/react-laag#77]
**Is your feature request related to a problem? Please describe.**
Using `useHover` hook, I'm trying to add a link or button into tooltip.
But when I'm interacting with the link or button, tooltip just closes on mobile devices

**Describe the solution you'd like**
It would be great, if tooltip don't close, while interacting with it, when trigger type is `hover` on mobile devices

Thanks.

**Comment by btravel** [comment]
Have the same issue. Suggested solution from #65 doesn't work cause there is an embedded in effect 'touchEnd' event handler that works on capture phase. Seems there is no way to override it from outside:


    function onTouchEnd() {
      if (show) {
        removeTimeout();
        setShow(false);
      }
    }

    window.addEventListener("touchend", onTouchEnd, true);
