### ISSUE TITLE
[BUG] React-18 Support

### ISSUE THREAD

**Issue by msdrigg** [everweij/react-laag#89]
**Describe the bug**
Update peerDependencies to support react 18.

**To Reproduce**
1. Add react-laag into a project with react 18
2. Try to compile
3. Note that there is warnings and/or errors

**Expected behavior**
React-Laag should support react 18

**Additional context**
I have been using react-laag with react-18 for a bit now, and it works. I don't know if there are any subtle issues I haven't noticed, but it seems to work great.

**Comment by rokasce** [comment]
Any updates on the issue?

**Comment by reintroducing** [comment]
there is a PR https://github.com/everweij/react-laag/pull/90 open with an apparent fix. It would be great to get it merged and close this out.

**Comment by everweij** [comment]
PR #90 just got merged, so I'm closing this issue. Feel free to open this issue again if you are experiencing any React 18 related issues.
